version: '3.5'

services:
  # create_database:
  #   container_name: create_database
  #   build: ./app
  postgres_db:
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.1-alpine
# docker-compose up --build   # Это строка выполнения при самом первом запуске "docker-compose.yaml"